name: guides
channels:
  - conda-forge
  - nodefaults
dependencies:
  - jupytext=1.16.7
  - linkify-it-py=2.0.3
  - myst-nb=1.2.0
  - nb-clean=4.0.1
  - pydata-sphinx-theme=0.16.0
  - pygit2=1.17.0
  - python=3.13.2
  - python-frontmatter=1.1.0
  - sphinx=8.2.3
  - sphinx-autobuild=2024.10.3
  - sphinx-copybutton=0.5.2
  - sphinx-design=0.6.1
  - sphinx-external-toc=1.0.1
  - sphinx-notfound-page=1.0.4
